name: Docker Build and Run

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on any tag  
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Dowload Ant and Ivy
        run: |
          sudo apt-get install openjdk-17-jdk
          sudo apt-get install -y ant curl
          sudo apt-get clean
          cd /usr
          sudo mkdir ivy
          curl -L https://dlcdn.apache.org/ant/ivy/2.5.2/apache-ivy-2.5.2-bin.tar.gz | sudo tar xz -C /usr/ivy
          cd ivy/
          cd apache-ivy-2.5.2/
          sudo cp *.jar /usr/share/ant/lib
      
      - name: Build Ant
        run: ant dist

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tetrisant:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      
  push:
    steps:
      -name: Push to Docker Hub
       if: startsWith(github.ref, 'refs/tags/') && github.ref_name =~ '^[0-9]+\.[0-9]+\.[0-9]+$'
       uses: docker/build-push-action@v2
       with:
        context: .
        dockerfile: dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tetrisant:today  

          