name: Docker Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Dowload Ant and Ivy
        run: |
          sudo apt-get install openjdk-17-jdk
          echo "salit 1"
          sudo apt-get install -y ant curl
          echo "salit 2"
          sudo apt-get clean
          mkdir -p /usr/local/ivy
          curl -L https://dlcdn.apache.org/ant/ivy/2.5.2/apache-ivy-2.5.2-bin.tar.gz | tar xz -C /usr/local/ivy --strip-components=1
          mv /usr/local/ivy/ivy-2.5.2.jar /usr/local/ivy/ivy.jar
      
      - name: Build Ant
        run: ant dist

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          push: false
          tags: myImage:latest

