name: Docker Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Dowload Ant and Ivy
        run: |
          sudo apt-get install openjdk-17-jdk
          echo "salit 1"
          pwd
          sudo apt-get install -y ant curl
          echo "salit 2"
          sudo apt-get clean
          which ant
          TEMP_DIR=$(mktemp -d)
          curl -L https://dlcdn.apache.org/ant/ivy/2.5.2/apache-ivy-2.5.2-bin.tar.gz | tar xz -C "$TEMP_DIR"
          sudo mv "$TEMP_DIR/ivy-2.5.2.jar" /usr/ivy.jar
          rm -rf "$TEMP_DIR"
      
      - name: Build Ant
        run: ant dist

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: dockerfile
          push: false
          tags: myImage:latest

